=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2026] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=head1 CONTACT

 Ensembl <http://www.ensembl.org/info/about/contact/index.html>

=cut

=head1 NAME

AVI - annotate variants with AVI scores

=head1 SYNOPSIS

 mv AVI.pm ~/.vep/Plugins
 ./vep -i variations.vcf --plugin AVI,file=/FULL_PATH/avi_scores.tsv.gz
 ./vep -i variations.vcf --plugin AVI,file=/FULL_PATH/avi_scores.tsv.gz,raw=1
 ./vep -i variations.vcf --plugin AVI,file=/FULL_PATH/avi_scores.tsv.gz,links=1

=head1 DESCRIPTION

 An Ensembl VEP plugin that retrieves AlphaGenome Variant Impact (AVI) scores for single nucleotide variants
 from a tabix-indexed, bgzip-compressed TSV file.

 AVI scores were developed by Google DeepMind and are available for commercial and non-commercial use. They
 are available from : https://deepmind.google.com/science/alphagenome/downloads.

 Details on the features contributing to AVI scores can be accessed via Google DeepMind's AlphaGenome Atlas,
 which is available for non-commercial use. An example variant URL is:
 https://deepmind.google.com/science/alphagenome/atlas?q=chr11:5225450:A>T&m=variant

 The PHRED score is reported by default as AVI_PHRED. The optional raw=1 parameter additionally reports the
 RAW score as AVI_RAW. The optional links=1 parameter reports an AVI_LINK URL to the variant in the
 AlphaGenome Atlas. Links are not generated by default; links=0 explicitly disables them.

 Score summaries:

 AVI_RAW (approximately -1.3 to +4.0). Variants with higher scores are more likely to have a deleterious
 impact.

 AVI_PHRED (0 to approximately 80) PHRED-scaled quantile. A phred of 20 means the variant is among the top 1%
 most deleterious substitutions genome-wide. Variants with higher scores are more likely to have a
 deleterious impact.

=cut

package AVI;

use strict;
use warnings;

use Bio::EnsEMBL::Variation::Utils::Sequence qw(get_matched_variant_alleles);
use Bio::EnsEMBL::Variation::Utils::BaseVepTabixPlugin;

use base qw(Bio::EnsEMBL::Variation::Utils::BaseVepTabixPlugin);

my %SCORE_INFO = (
  phred => {
    name => 'AVI_PHRED',
    description => 'PHRED-scaled quantile (0 to approximately 80). A phred of 20 means the variant is among the top 1% most deleterious substitutions genome-wide. Higher => more deleterious.',
  },
  raw_score => {
    name => 'AVI_RAW',
    description => 'Raw score (approximately -1.3 to +4.0). Higher => more deleterious.',
  },
);

my $LINK_NAME = 'AVI_LINK';
my $ATLAS_URL = 'https://deepmind.google.com/science/alphagenome/atlas';

sub new {
  my $class = shift;
  my $self = $class->SUPER::new(@_);

  $self->expand_left(0);
  $self->expand_right(0);
  $self->get_user_params();

  my $params = $self->params_to_hash();
  my ($positional_file) = grep { index($_, '=') == -1 } @{$self->params};
  my $file = $params->{file} || $positional_file;

  die "ERROR: No AVI file specified\n" unless $file;

  $self->{include_raw} = _enabled($params->{raw});
  $self->{include_links} = _enabled($params->{links});
  $self->add_file($file);

  return $self;
}

sub feature_types {
  return ['Feature', 'Intergenic'];
}

sub get_header_info {
  my $self = shift;

  my %header = (
    $SCORE_INFO{phred}->{name} => $SCORE_INFO{phred}->{description},
  );

  $header{$SCORE_INFO{raw_score}->{name}} = $SCORE_INFO{raw_score}->{description}
    if $self->{include_raw};
  $header{$LINK_NAME} = 'Link to the variant in the Google DeepMind AlphaGenome Atlas'
    if $self->{include_links};

  return \%header;
}

sub run {
  my ($self, $tva) = @_;

  my $vf = $tva->variation_feature;
  my ($start, $end) = ($vf->{start}, $vf->{end});
  my $ref = $vf->ref_allele_string;
  my $allele = $tva->variation_feature_seq;

  return {} unless defined($start) && defined($end) && $start == $end;
  return {} unless defined($ref) && $ref =~ /^[ACGT]$/;
  return {} unless defined($allele) && $allele =~ /^[ACGT]$/;

  foreach my $record (@{$self->get_data($vf->{chr}, $start, $end)}) {
    my $matches = get_matched_variant_alleles(
      {
        ref    => $ref,
        alts   => [$allele],
        pos    => $start,
        strand => $vf->strand,
      },
      {
        ref  => $record->{ref},
        alts => [$record->{alt}],
        pos  => $record->{start},
      }
    );

    return $record->{result} if @{$matches};
  }

  return {};
}

sub parse_data {
  my ($self, $line) = @_;
  my ($chr, $start, $ref, $alt, $raw, $phred) = split /\t/, $line, 7;

  return unless defined($phred);

  my %result = (
    $SCORE_INFO{phred}->{name} => $phred,
  );

  $result{$SCORE_INFO{raw_score}->{name}} = $raw if $self->{include_raw};

  if ($self->{include_links}) {
    my $link_chr = $chr =~ /^chr/i ? $chr : 'chr' . $chr;
    $result{$LINK_NAME} = sprintf('%s?q=%s:%s:%s>%s&m=variant', $ATLAS_URL, $link_chr, $start, $ref, $alt);
  }

  return {
    chr    => $chr,
    start  => $start,
    end    => $start,
    ref    => $ref,
    alt    => $alt,
    result => \%result,
  };
}

sub get_start {
  return $_[1]->{start};
}

sub get_end {
  return $_[1]->{end};
}

sub _enabled {
  my $value = shift;
  return defined($value) && $value =~ /^(?:1|true|yes)$/i;
}

1;
